export const GUIDELINES_SCREEN = "GUIDELINES_SCREEN";
export const LOCATION_SELECT_SCREEN = "LOCATION_SELECT_SCREEN";
export const INFO_SCREEN = "INFO_SCREEN";
export const EDIT_INFO_SCREEN = "EDIT_INFO_SCREEN";
